tasks:
  - init: yarn install && yarn run build
    command: yarn run start
  - command: >
      while [ -z "$SAUCE_USERNAME" ] ; do
        printf "\n❗ The SAUCE_USERNAME environment variable is required. Please enter its value.\n" &&
        read USERNAME ;
      done ; gp env SAUCE_USERNAME=$USERNAME && printf "\nThanks\n"
      # Now you can use $SAUCE_USERNAME
  - command: >
      while [ -z "$SAUCE_ACCESS_KEY" ] ; do
        printf "\n❗ The SAUCE_ACCESS_KEY environment variable is required. Please enter its value.\n" &&
        read KEY ;
      done ; gp env SAUCE_ACCESS_KEY=$KEY && printf "\nThanks\n"
      # Now you can use $SAUCE_ACCESS_KEY
image:
  file: .gitpod.Dockerfile
