tasks:
  - init: yarn install && yarn run build
    command: yarn run start
  - command: >
      while [ -z "$SAUCE_USERNAME" ] ; do
        printf "\n❗ The SAUCE_USERNAME environment variable is required. Please enter its value.\n" &&
        read -s -p "SAUCE_USERNAME: " SAUCE_USERNAME ;
      done ; gp env SAUCE_USERNAME=$SAUCE_USERNAME && printf "\nThanks\n" ;
      while [ -z "$SAUCE_ACCESS_KEY" ] ; do
        printf "\n❗ The SAUCE_ACCESS_KEY environment variable is required. Please enter its value.\n" &&
        read -s -p "SAUCE_ACCESS_KEY: " SAUCE_ACCESS_KEY ;
      done ; gp env SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY && printf "\nThanks\n" ;
image:
  file: .gitpod.Dockerfile
